// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtncpahwwevyxvzcwvxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0bmNwYWh3d2V2eXh2emN3dnh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMzQ5OTksImV4cCI6MjA2MTYxMDk5OX0.qKmRasSkKHwtwAwQ46lHTqbJiQlF9N3saAggT2X4DM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);